version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: oms_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: oms
      MYSQL_DATABASE: oms
      MYSQL_USER: oms
      MYSQL_PASSWORD: oms
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
